export const tagTypes = {
  auth: "Auth",
  users: "Users",
  user: "User",
  otp: "Otp",
  products: "Products",
  product: "Product",
  orders: "Orders",
  order: "Order",
  content: "Content",
  notification: "Notification",
  package: "Package",
  earnings: "Earnings",
  instructors: "Instructors",
  courses: "Courses",
  course: "Course",
  categories: "Categories",
  bookings: "Bookings",
  attendance: "Attendance",
  appLaunchRegisteredUsers: "AppLaunchRegisteredUsers",
  dashboardData: "DashboardData",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.users,
  tagTypes.user,
  tagTypes.otp,
  tagTypes.products,
  tagTypes.product,
  tagTypes.orders,
  tagTypes.order,
  tagTypes.content,
  tagTypes.notification,
  tagTypes.package,
  tagTypes.subcategory,
  tagTypes.earnings,
  tagTypes.instructors,
  tagTypes.courses,
  tagTypes.course,
  tagTypes.categories,
  tagTypes.bookings,
  tagTypes.attendance,
  tagTypes.appLaunchRegisteredUsers,
  tagTypes.dashboardData,
];
